---
actions:
  to: kubernetes/overlays/local/deployment.yaml
---
# Generated on {{now}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{artifactId}}
spec:
  selector:
    matchLabels:
      app: {{artifactId}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{artifactId}}
    spec:
      containers:
        - name: {{artifactId}}
          image: lift/{{artifactId}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
