---
actions:
  to: kubernetes/overlays/local/kustomization.yaml
---
# name prefix should corresponse to the profile name as a convention
namePrefix: local-
commonLabels:
  app.kubernetes.io/name: {{artifactId}}
resources:
  - deployment.yaml
  - service.yaml
